### Задание 1
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
	- оценка 2 и меньше - низкий рейтинг
	- оценка 4 и меньше - средний рейтинг
	- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [1]:
import pandas as pd

In [113]:
movie = pd.read_csv(r'C:\Users\aekom\Lessons\12 Pandas\ml-25m\movies.csv')
rating = pd.read_csv(r'C:\Users\aekom\Lessons\12 Pandas\ml-25m\ratings.csv')

In [114]:
movie.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [115]:
rating.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [120]:
rating = rating.groupby('movieId').mean().sort_values('movieId', ascending=True).reset_index()
rating.head(50)

    movieId        userId    rating     timestamp
0         1  81294.564728  3.893708  1.153152e+09
1         2  81358.542554  3.251527  1.122310e+09
2         3  81343.694934  3.142028  9.806023e+08
3         4  81266.193024  2.853547  9.424605e+08
4         5  81002.872460  3.058434  1.004723e+09
5         6  81279.690540  3.854909  1.073897e+09
6         7  81322.521348  3.363666  9.788326e+08
7         8  78277.924851  3.114583  9.771905e+08
8         9  81391.846403  2.992051  9.413482e+08
9        10  81340.038281  3.421458  1.030352e+09
10       11  81374.336991  3.657171  9.852080e+08
11       12  82345.860198  2.624566  1.020829e+09
12       13  80071.048397  3.333528  1.142143e+09
13       14  82500.626974  3.423489  9.366612e+08
14       15  82200.693116  2.719022  1.001111e+09
15       16  81193.517007  3.823707  1.118345e+09
16       17  81299.266765  3.948806  9.986121e+08
17       18  81231.610532  3.384351  1.084555e+09
18       19  81248.297606  2.642168  1.093685e+09
19       20  81646.374479  2.869922  1.001036e+09
20       21  81181.014499  3.570162  9.792793e+08
21       22  81504.464437  3.320017  9.931630e+08
22       23  82032.575949  3.145691  1.013575e+09
23       24  81020.768591  3.187584  1.037070e+09
24       25  81184.603837  3.677304  9.891319e+08
25       26  81701.083562  3.606709  9.605511e+08
26       27  80644.956246  3.403932  1.013521e+09
27       28  81287.253559  4.030000  1.005712e+09
28       29  81144.594702  3.936725  1.114292e+09
29       30  82838.190395  3.636792  9.376807e+08
30       31  81013.575225  3.244839  1.051671e+09
31       32  81345.296829  3.905768  1.102232e+09
32       33  81105.892308  3.023077  1.020321e+09
33       34  80992.355512  3.603192  1.037780e+09
34       35  81354.497041  3.479290  9.215664e+08
35       36  81144.957138  3.918687  9.896148e+08
36       37  77956.360000  2.993333  9.985759e+08
37       38  81268.058637  2.870840  1.104123e+09
38       39  81122.111895  3.418738  1.051097e+09
39       40  84022.774153  3.626725  9.247420e+08
40       41  81540.600328  3.843413  9.430985e+08
41       42  80156.856522  3.049565  9.886344e+08
42       43  83322.959272  3.449957  9.311865e+08
43       44  81614.919654  2.654624  1.076571e+09
44       45  81100.880973  3.382908  9.782339e+08
45       46  80940.183454  3.263413  9.431739e+08
46       47  81283.299846  4.079166  1.161512e+09
47       48  81700.920140  2.977751  1.096454e+09
48       49  79820.719298  3.519737  1.085270e+09
49       50  81374.886952  4.284353  1.173488e+09

In [117]:
def my_rating(my_rating):
    if my_rating >= 4.5:
        return 'Высокий рейтинг'
    elif 2 < my_rating <= 4:
        return 'Средний рейтинг'
    elif my_rating <= 2:
        return 'Низкий рейтинг'
    else:
        return 'Условие не задано' # 4.0 - 4.5 по условию задачи

In [121]:
movie['Class'] = rating['rating'].apply(my_rating)
movie.head(50)

,movieId,title,genres,Class
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Средний рейтинг
1,2,Jumanji (1995),Adventure|Children|Fantasy,Средний рейтинг
2,3,Grumpier Old Men (1995),Comedy|Romance,Средний рейтинг
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Средний рейтинг
4,5,Father of the Bride Part II (1995),Comedy,Средний рейтинг
5,6,Heat (1995),Action|Crime|Thriller,Средний рейтинг
6,7,Sabrina (1995),Comedy|Romance,Средний рейтинг
7,8,Tom and Huck (1995),Adventure|Children,Средний рейтинг
8,9,Sudden Death (1995),Action,Средний рейтинг
9,10,GoldenEye (1995),Action|Adventure|Thriller,Средний рейтинг
10,11,"American President, The (1995)",Comedy|Drama|Romance,Средний рейтинг
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror,Средний рейтинг
12,13,Balto (1995),Adventure|Animation|Children,Средний рейтинг
13,14,Nixon (1995),Drama,Средний рейтинг
14,15,Cutthroat Island (1995),Action|Adventure|Romance,Средний рейтинг
15,16,Casino (1995),Crime|Drama,Средний рейтинг
16,17,Sense and Sensibility (1995),Drama|Romance,Средний рейтинг
17,18,Four Rooms (1995),Comedy,Средний рейтинг
18,19,Ace Ventura: When Nature Calls (1995),Comedy,Средний рейтинг
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,Средний рейтинг
20,21,Get Shorty (1995),Comedy|Crime|Thriller,Средний рейтинг
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller,Средний рейтинг
22,23,Assassins (1995),Action|Crime|Thriller,Средний рейтинг
23,24,Powder (1995),Drama|Sci-Fi,Средний рейтинг
24,25,Leaving Las Vegas (1995),Drama|Romance,Средний рейтинг
25,26,Othello (1995),Drama,Средний рейтинг
26,27,Now and Then (1995),Children|Drama,Средний рейтинг
27,28,Persuasion (1995),Drama|Romance,Условие не задано
28,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,Средний рейтинг
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama,Средний рейтинг
30,31,Dangerous Minds (1995),Drama,Средний рейтинг
31,32,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,Средний рейтинг
32,33,Wings of Courage (1995),Adventure|Romance|IMAX,Средний рейтинг
33,34,Babe (1995),Children|Drama,Средний рейтинг
34,35,Carrington (1995),Drama|Romance,Средний рейтинг
35,36,Dead Man Walking (1995),Crime|Drama,Средний рейтинг
36,37,Across the Sea of Time (1995),Documentary|IMAX,Средний рейтинг
37,38,It Takes Two (1995),Children|Comedy,Средний рейтинг
38,39,Clueless (1995),Comedy|Romance,Средний рейтинг
39,40,"Cry, the Beloved Country (1995)",Drama,Средний рейтинг
40,41,Richard III (1995),Drama|War,Средний рейтинг
41,42,Dead Presidents (1995),Action|Crime|Drama,Средний рейтинг
42,43,Restoration (1995),Drama,Средний рейтинг
43,44,Mortal Kombat (1995),Action|Adventure|Fantasy,Средний рейтинг
44,45,To Die For (1995),Comedy|Drama|Thriller,Средний рейтинг
45,46,How to Make an American Quilt (1995),Drama|Romance,Средний рейтинг
46,47,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,Условие не задано
47,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance,Средний рейтинг
48,49,When Night Is Falling (1995),Drama|Romance,Средний рейтинг
49,50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,Условие не задано

# Учитель!!!

в решении выше первое значение возвращает NaN, если не использовать reset_index(). Получается, что остальные значения также съезжают на 1 строчку, верно?
rating = rating.groupby('movieId').mean().sort_values('movieId', ascending=True).reset_index()

In [124]:
movie = pd.read_csv(r'C:\Users\aekom\Lessons\12 Pandas\ml-25m\movies.csv')
rating = pd.read_csv(r'C:\Users\aekom\Lessons\12 Pandas\ml-25m\ratings.csv')
joined = movie.merge(rating, on='movieId', how='left')
joined.head(50)

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,2.0,3.5,1.141416e+09
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.0,4.0,1.439472e+09
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,4.0,3.0,1.573944e+09
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.586259e+08
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,8.0,4.0,8.904925e+08
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10.0,3.5,1.227571e+09
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,12.0,4.0,1.167583e+09
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13.0,4.0,1.265224e+09
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18.0,3.0,1.108273e+09
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,26.0,3.0,1.280516e+09
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,36.0,5.0,8.571314e+08
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,43.0,4.0,1.170491e+09
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,47.0,2.0,8.550938e+08
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,50.0,4.0,1.402505e+09
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,51.0,4.0,1.510743e+09
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,56.0,2.0,1.166776e+09
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,57.0,4.0,1.142403e+09
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,64.0,4.0,1.434644e+09
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,66.0,3.0,1.138601e+09
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,67.0,3.0,9.756616e+08
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,69.0,3.0,1.242591e+09
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,73.0,3.0,8.578298e+08
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,75.0,5.0,1.537208e+09
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,77.0,4.0,8.320215e+08
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,82.0,4.0,1.437241e+09
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,86.0,5.0,9.454628e+08
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,90.0,5.0,8.635380e+08
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,93.0,5.0,1.496543e+09
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,95.0,5.0,1.510351e+09
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,96.0,5.0,1.443313e+09
30,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,98.0,5.0,1.450047e+09
31,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,109.0,4.0,1.545624e+09
32,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,110.0,4.0,1.437791e+09
33,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,111.0,4.5,1.167222e+09
34,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,112.0,3.0,8.640741e+08
35,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,120.0,5.0,9.562646e+08
36,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,125.0,4.0,1.023425e+09
37,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,127.0,5.0,1.433014e+09
38,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,130.0,3.0,8.884576e+08
39,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,132.0,4.0,1.013955e+09
40,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,143.0,5.0,8.606121e+08
41,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,147.0,4.0,9.387688e+08
42,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,152.0,5.0,9.939321e+08
43,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,158.0,5.0,8.354851e+08
44,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,160.0,4.5,1.174082e+09
45,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,162.0,5.0,1.001111e+09
46,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,163.0,3.5,1.200698e+09
47,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,166.0,4.0,9.420147e+08
48,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,167.0,4.0,8.602245e+08
49,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,171.0,4.5,1.074594e+09

In [125]:
joined =  joined.groupby('movieId').mean().sort_values('movieId', ascending=True)
joined.head()

               userId    rating     timestamp
movieId
1        81294.564728  3.893708  1.153152e+09
2        81358.542554  3.251527  1.122310e+09
3        81343.694934  3.142028  9.806023e+08
4        81266.193024  2.853547  9.424605e+08
5        81002.872460  3.058434  1.004723e+09

In [126]:
def my_rating(my_rating):
    if my_rating >= 4.5:
        return 'Высокий рейтинг'
    elif 2 < my_rating < 4:
        return 'Средний рейтинг'
    elif my_rating <= 2:
        return 'Низкий рейтинг'
    else:
        return 'Условие не задано' # 4.0 - 4.5 по условию задачи

In [127]:
joined['Class'] = joined['rating'].apply(my_rating)
joined.head(50)

               userId    rating     timestamp              Class
movieId
1        81294.564728  3.893708  1.153152e+09    Средний рейтинг
2        81358.542554  3.251527  1.122310e+09    Средний рейтинг
3        81343.694934  3.142028  9.806023e+08    Средний рейтинг
4        81266.193024  2.853547  9.424605e+08    Средний рейтинг
5        81002.872460  3.058434  1.004723e+09    Средний рейтинг
6        81279.690540  3.854909  1.073897e+09    Средний рейтинг
7        81322.521348  3.363666  9.788326e+08    Средний рейтинг
8        78277.924851  3.114583  9.771905e+08    Средний рейтинг
9        81391.846403  2.992051  9.413482e+08    Средний рейтинг
10       81340.038281  3.421458  1.030352e+09    Средний рейтинг
11       81374.336991  3.657171  9.852080e+08    Средний рейтинг
12       82345.860198  2.624566  1.020829e+09    Средний рейтинг
13       80071.048397  3.333528  1.142143e+09    Средний рейтинг
14       82500.626974  3.423489  9.366612e+08    Средний рейтинг
15       82200.693116  2.719022  1.001111e+09    Средний рейтинг
16       81193.517007  3.823707  1.118345e+09    Средний рейтинг
17       81299.266765  3.948806  9.986121e+08    Средний рейтинг
18       81231.610532  3.384351  1.084555e+09    Средний рейтинг
19       81248.297606  2.642168  1.093685e+09    Средний рейтинг
20       81646.374479  2.869922  1.001036e+09    Средний рейтинг
21       81181.014499  3.570162  9.792793e+08    Средний рейтинг
22       81504.464437  3.320017  9.931630e+08    Средний рейтинг
23       82032.575949  3.145691  1.013575e+09    Средний рейтинг
24       81020.768591  3.187584  1.037070e+09    Средний рейтинг
25       81184.603837  3.677304  9.891319e+08    Средний рейтинг
26       81701.083562  3.606709  9.605511e+08    Средний рейтинг
27       80644.956246  3.403932  1.013521e+09    Средний рейтинг
28       81287.253559  4.030000  1.005712e+09  Условие не задано
29       81144.594702  3.936725  1.114292e+09    Средний рейтинг
30       82838.190395  3.636792  9.376807e+08    Средний рейтинг
31       81013.575225  3.244839  1.051671e+09    Средний рейтинг
32       81345.296829  3.905768  1.102232e+09    Средний рейтинг
33       81105.892308  3.023077  1.020321e+09    Средний рейтинг
34       80992.355512  3.603192  1.037780e+09    Средний рейтинг
35       81354.497041  3.479290  9.215664e+08    Средний рейтинг
36       81144.957138  3.918687  9.896148e+08    Средний рейтинг
37       77956.360000  2.993333  9.985759e+08    Средний рейтинг
38       81268.058637  2.870840  1.104123e+09    Средний рейтинг
39       81122.111895  3.418738  1.051097e+09    Средний рейтинг
40       84022.774153  3.626725  9.247420e+08    Средний рейтинг
41       81540.600328  3.843413  9.430985e+08    Средний рейтинг
42       80156.856522  3.049565  9.886344e+08    Средний рейтинг
43       83322.959272  3.449957  9.311865e+08    Средний рейтинг
44       81614.919654  2.654624  1.076571e+09    Средний рейтинг
45       81100.880973  3.382908  9.782339e+08    Средний рейтинг
46       80940.183454  3.263413  9.431739e+08    Средний рейтинг
47       81283.299846  4.079166  1.161512e+09  Условие не задано
48       81700.920140  2.977751  1.096454e+09    Средний рейтинг
49       79820.719298  3.519737  1.085270e+09    Средний рейтинг
50       81374.886952  4.284353  1.173488e+09  Условие не задано

### Задание 2
Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце 'region' пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим 'undefined'.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

    'Центр': ['москва', 'тула', 'ярославль'],

    'Северо-Запад': ['петербург', 'псков', 'мурманск'],

    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

}

Результат классификации запишите в отдельный столбец region.

In [133]:
my_keywords = pd.read_csv(r'C:\Users\aekom\Lessons\12 Pandas\keywords.csv')
my_keywords.head()

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [188]:
geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

i = 0
def fill_out_region_with(my_keywords):
    keywords = my_keywords.split(' ')
    for word in keywords:
        for key, value in geo_data.items():
            if word in value:                
                return key
            return 'undefined'

In [190]:
my_keywords['Регион'] = my_keywords['keyword'].apply(fill_out_region_with)
my_keywords.sort_values('Регион', ascending=False).head(50)

                                                 keyword   shows     Регион
70611                       москва 24 онлайн прямой эфир    5055      Центр
44863                      москва симферополь авиабилеты   16043      Центр
68181                  москва слезам не верит фильм 1980    5173      Центр
74372                                       москва 3 рим    5057      Центр
59617                      москва слезам не верит актеры    6408      Центр
98183                москва октябрьская это какой вокзал    3696      Центр
83053           москва слезам не верит фильм 1980 актеры    4320      Центр
7103                                         москва сити   37022      Центр
81003                    москва я терплю тебя фильм 2016    4468      Центр
92517                                   ярославль погода   31930      Центр
6999                                           москва 24   37459      Центр
40095                                       москва время   39941      Центр
11785                                               тула   23898      Центр
87259                                        москва сочи    4822      Центр
85584                                    москва панорама    4396      Центр
16175  москва слезам не верит смотреть в хорошем каче...   18407      Центр
39920                                       москва карта   15769      Центр
74724                                       москва минск    6023      Центр
93819                             москва нижний новгород    6220      Центр
1259                                              москва  153050      Центр
18843                                          москва фм   16400      Центр
5983                                   москва третий рим   43182      Центр
8132                                       москва погода  151701      Центр
52463                             москва санкт петербург    9756      Центр
71891  москва слезам не верит смотреть бесплатно в хо...    5167      Центр
47121                             москва сочи авиабилеты   13146      Центр
7339                              москва слезам не верит   35857      Центр
55882                    ярославль достопримечательности    6306      Центр
66224                                   москва сити фото    6086      Центр
6075                                           ярославль   41720      Центр
45309             москва слезам не верит смотреть онлайн    7976      Центр
52727                москва третий рим православный сайт    6630      Центр
57421                                       москва метро   68024      Центр
93321                                       москва авито  979292      Центр
66675                                 знахарь фильм 1982    5295  undefined
66674           работа в железнодорожном свежие вакансии    5370  undefined
66619                                5из36 архив тиражей    5338  undefined
66673           размер материнского капитала в 2017 году    5419  undefined
66620                      гисметео смоленск на 2 недели    5381  undefined
66672                                              армед    5280  undefined
66671                  электронная очередь в детский сад    5303  undefined
66669                                      паукообразные    5280  undefined
66621                   адмирал динамо мн 16 января 2017    5283  undefined
66670                               мюзикл анна каренина   12326  undefined
66677               украина в огне оливер стоун смотреть    5141  undefined
66668                                  плинтус напольный    5632  undefined
66667                                 скачать песню с вк    5360  undefined
66666                                               a ha    5283  undefined
66665                                      озерки аптека   26293  undefined
66622                                            веб той    5283  undefined

### Задание 3 (бонусное)
Есть мнение, что "раньше снимали настоящее кино, не то что сейчас". Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

1. В переменную years запишите список из всех годов с 1950 по 2010.

2. Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:
	- для каждой строки пройдите по всем годам списка years
	- если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
	- если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год

3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец 'year'

4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца 'year' и отсортируйте результат по убыванию рейтинга

In [10]:
years = [str(year) for year in range(1950, 2011)]

In [11]:
movies = pd.read_csv(r'C:\Users\aekom\Lessons\12 Pandas\ml-25m\movies.csv')

In [12]:
import re

In [13]:
def production_year(movies):
    words = movies.split(' ')
    for word in words:
        if re.findall(r'\d{4}', word):
            year_in_title = str(re.findall(r'\d{4}', word)[0])
            if year_in_title in years:
                return year_in_title
            return '1900'

# Мастер!

Можно ли тут сократить код, чтобы два раза не писать одно и то же?

        if re.findall(r'\d{4}', word):
        
            year_in_title = str(re.findall(r'\d{4}', word)[0])

In [14]:
movies['Year'] = movies['title'].apply(production_year)
movies.head()

,movieId,title,genres,Year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995

In [25]:
ratings = pd.read_csv(r'C:\Users\aekom\Lessons\12 Pandas\ml-25m\ratings.csv')

In [26]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [28]:
ratings = ratings.groupby('movieId').mean().reset_index()
ratings.head()

   movieId        userId    rating     timestamp
0        1  81294.564728  3.893708  1.153152e+09
1        2  81358.542554  3.251527  1.122310e+09
2        3  81343.694934  3.142028  9.806023e+08
3        4  81266.193024  2.853547  9.424605e+08
4        5  81002.872460  3.058434  1.004723e+09

In [43]:
joined = movies.merge(ratings, on='movieId', how='left')
joined.head(10)

,movieId,title,genres,Year,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995,81294.564728,3.893708,1.153152e+09
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995,81358.542554,3.251527,1.122310e+09
2,3,Grumpier Old Men (1995),Comedy|Romance,1995,81343.694934,3.142028,9.806023e+08
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995,81266.193024,2.853547,9.424605e+08
4,5,Father of the Bride Part II (1995),Comedy,1995,81002.872460,3.058434,1.004723e+09
5,6,Heat (1995),Action|Crime|Thriller,1995,81279.690540,3.854909,1.073897e+09
6,7,Sabrina (1995),Comedy|Romance,1995,81322.521348,3.363666,9.788326e+08
7,8,Tom and Huck (1995),Adventure|Children,1995,78277.924851,3.114583,9.771905e+08
8,9,Sudden Death (1995),Action,1995,81391.846403,2.992051,9.413482e+08
9,10,GoldenEye (1995),Action|Adventure|Thriller,1995,81340.038281,3.421458,1.030352e+09

In [52]:
joined[joined['Year'].isin(years)].sort_values('rating', ascending=False).head(50)

,movieId,title,genres,Year,userId,rating,timestamp
50063,180193,Podstrochnik (2009),(no genres listed),2009,161087.0,5.0,1.510178e+09
57626,196787,The Law and the Fist (1964),Drama|War,1964,124818.0,5.0,1.545602e+09
30799,137050,The Rival (2006),Thriller,2006,97460.0,5.0,1.436145e+09
26856,127345,Rio Diablo (1993),Western,1993,18580.0,5.0,1.476625e+09
59918,201981,Little House: Look Back to Yesterday (1983),Children|Drama|Romance|Western,1983,111934.0,5.0,1.557661e+09
59914,201971,Grindstone Road (2008),Thriller,2008,75309.0,5.0,1.558738e+09
30798,137048,Perfect Child (2007),Drama,2007,97460.0,5.0,1.436145e+09
30793,137038,The Perfect Wife (2001),Drama|Thriller,2001,97460.0,5.0,1.436144e+09
30790,137032,The Perfect Neighbor (2005),Drama|Thriller,2005,97460.0,5.0,1.436144e+09
57072,195549,The Monster of Phantom Lake (2006),Comedy|Horror,2006,24869.0,5.0,1.542056e+09
24126,120735,Love Chronicles (2003),Drama|Romance,2003,75309.0,5.0,1.558738e+09
59887,201901,White Rush (2003),Action|Crime|Thriller,2003,75309.0,5.0,1.558738e+09
49157,178217,Hempsters: Plant the Seed (2008),Documentary,2008,75309.0,5.0,1.558738e+09
27806,130206,Picture Mommy Dead (1966),Horror,1966,75309.0,5.0,1.558738e+09
25367,123569,Tempo (2003),Crime|Romance|Thriller,2003,93885.0,5.0,1.501380e+09
59864,201821,Civilisation (1969),(no genres listed),1969,150180.0,5.0,1.560271e+09
30787,137026,Tainted Blood (1993),Mystery|Thriller,1993,97460.0,5.0,1.436143e+09
30786,137024,The Perfect Nanny (2000),Thriller,2000,97460.0,5.0,1.436143e+09
39330,156954,Don't Let the Angels Fall (1969),(no genres listed),1969,72315.0,5.0,1.563300e+09
59848,201781,Dawning (2009),Horror|Thriller,2009,75309.0,5.0,1.558738e+09
16463,86975,As Seen Through These Eyes (2008),Documentary,2008,75309.0,5.0,1.558738e+09
30773,136996,The Wrong Girl (1999),Drama|Thriller,1999,97460.0,5.0,1.436140e+09
30771,136992,When He Didn't Come Home (1998),(no genres listed),1998,97460.0,5.0,1.436140e+09
30800,137052,A Job to Kill For (2006),Drama|Thriller,2006,97460.0,5.0,1.436145e+09
30805,137064,Twisted Desire (1996),Crime|Drama,1996,97460.0,5.0,1.436146e+09
32722,141578,Gang War (1958),Crime,1958,75309.0,5.0,1.558738e+09
26933,127717,Five for Hell (1969),Action|Drama|War,1969,75309.0,5.0,1.558738e+09
26991,128045,Reality Check (2002),Horror|Thriller,2002,75309.0,5.0,1.558738e+09
32592,141297,Out on a Limb (1987),(no genres listed),1987,119682.0,5.0,1.497366e+09
38936,155996,Alex: The Life of a Child (1986),Drama,1986,157275.0,5.0,1.459259e+09
32600,141313,Tarzan's Hidden Jungle (1955),Action|Adventure|Drama|Romance,1955,75309.0,5.0,1.558738e+09
60006,202211,Spike (2008),Fantasy|Horror|Romance|Sci-Fi,2008,75309.0,5.0,1.558738e+09
30834,137132,HottieBoombaLottie (2008),Comedy|Romance,2008,75309.0,5.0,1.558738e+09
49227,178417,A Lustful Man (1961),Comedy|Drama,1961,32253.0,5.0,1.506325e+09
43820,166900,Sondheim! The Birthday Concert (2010),(no genres listed),2010,149756.0,5.0,1.480978e+09
36864,151367,Twisted Seduction (2010),Comedy|Romance|Thriller,2010,220.0,5.0,1.453321e+09
59993,202181,Warlock Moon (1973),Horror|Thriller,1973,75309.0,5.0,1.558738e+09
39094,156414,Life Even Looks Like a Party (2009),Documentary,2009,158983.0,5.0,1.459611e+09
50779,181765,Forbidden Love: The Unashamed Stories of Lesbi...,Documentary,1992,117192.0,5.0,1.512598e+09
19040,99243,"Parasites, Les (1999)",Comedy,1999,56424.0,5.0,1.389027e+09
38961,156063,"Dance With Me, Henry (1956)",Comedy,1956,93517.0,5.0,1.524138e+09
30812,137078,Stranger in My House (1999),Thriller,1999,97460.0,5.0,1.436150e+09
26885,127592,Naked Angels (1969),Drama|Thriller,1969,75309.0,5.0,1.558738e+09
39056,156321,Lost in Alaska (1952),Comedy,1952,93517.0,5.0,1.524138e+09
53793,188153,The Undefeated (2000),Drama|War,2000,147687.0,5.0,1.525951e+09
61382,205741,Threshold (1982),Drama,1982,72315.0,5.0,1.568759e+09
45457,170429,9 Dalmuir West (1962),Documentary,1962,146281.0,5.0,1.490389e+09
25355,123541,Geordie (1955),Drama|Romance,1955,14300.0,5.0,1.490712e+09
52348,185085,The Legend of Earl Durand (1980),(no genres listed),1980,115229.0,5.0,1.520425e+09
39401,157116,"Ich Chef, Du Turnschuh (1998)",Comedy|Drama,1998,29089.0,5.0,1.516163e+09

# Сенсей!
когда я пишу путь до файла:
movie = pd.read_csv(r'C:\Users\aekom\Lessons\12 Pandas\ml-25m\movies.csv')
то я использую регулярку, ибо r'. Саму конструкцию подсмотрел в интернете и оно работает! Но разве не должен знак \ в пути к файлу экранировать следующий символ?

Спасибо, мастер!